"use strict";
exports.__esModule = true;
exports.contactsRouter = void 0;
var express = require("express");
var bodyParser = require("body-parser");
var contacts_controller_1 = require("../controllers/contacts-controller");
var parser = bodyParser.json();
var router = express.Router();
exports.contactsRouter = router;
var controller = new contacts_controller_1.ContactsController();
router.get('/get-contacts', controller.handleGetAll);
router.post('/set-contact', parser, controller.handleSetContact);
router.put('/update-contact', parser, controller.handleUpdateContact);
router["delete"]('/del-contact', parser, controller.handleDelContact);
